/* 
  Sketch generated by the Arduino IoT Cloud Thing "Home Garage"
  https://create.arduino.cc/cloud/things/cb22fa43-60c1-4bbc-b7e3-4163ffdf8730 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch garage_Close;
  CloudSwitch garage_Open;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since GarageOpen is READ_WRITE variable, onGarageOpenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGarageOpenChange()  {

  Serial.print(garage_Open);
  garage_Open = 0;
  //garage_Close = 1;
  door_up = true;
  status = 48;
  Serial.println(status);
  ArduinoCloud.update();
  delay(5000);
  Serial.print(garage_Open);
  //door_up = 0;
 // garage_Open = 0;
  ArduinoCloud.update();
  // Add your code here to act upon GarageOpen change
}

/*
  Since GarageClose is READ_WRITE variable, onGarageCloseChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGarageCloseChange()  {
  delay(2000);
  door_up = 0;
  //status = 25;
  Serial.print("2");
  
  // Add your code here to act upon GarageClose change
}


void onLightChange()  {
  // Add your code here to act upon Light change
}
