// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a769e9e1-96e4-4a10-bbbf-eff875d8bbcc";

const char SSID[]               = "Luke3573";    // Network SSID (name)
const char PASS[]               = "20062578";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "QMPRRVCglCHWzRP?6F7FGVeC2";    // Secret device password

void onGarageOpenChange();

CloudContactSensor door_up;
CloudLight door;
CloudSwitch garage_Open;
String status ;//= "hdhd";

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(door_up, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(door, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(garage_Open, READWRITE, 2 * SECONDS, onGarageOpenChange);
  ArduinoCloud.addProperty(status, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
