/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/63ae89c0-1cfc-47bc-8e2d-b46bcfd9efab 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String gate_Status;
  CloudContactSensor gate_Close;
  CloudContactSensor gate_Open;
  CloudSwitch front_Gate_Close;
  CloudSwitch front_Gate_Open;
  CloudSwitch front_Gate_Personal_Open;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since HomeGate is READ_WRITE variable, onHomeGateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHomeGateChange()  {
  // Add your code here to act upon HomeGate change
}

/*
  Since HomeGateOpen is READ_WRITE variable, onHomeGateOpenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHomeGateOpenChange()  {
  // Add your code here to act upon HomeGateOpen change
}

/*
  Since HomeGateClose is READ_WRITE variable, onHomeGateCloseChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHomeGateCloseChange()  {
  // Add your code here to act upon HomeGateClose change
}

/*
  Since HomeGatePersonalOpen is READ_WRITE variable, onHomeGatePersonalOpenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHomeGatePersonalOpenChange()  {
  // Add your code here to act upon HomeGatePersonalOpen change
}



/*
  Since GateStatus is READ_WRITE variable, onGateStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGateStatusChange()  {
  // Add your code here to act upon GateStatus change
}



/*
  Since FrontGateClose is READ_WRITE variable, onFrontGateCloseChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFrontGateCloseChange()  {
  // Add your code here to act upon FrontGateClose change
}

/*
  Since FrontGateOpen is READ_WRITE variable, onFrontGateOpenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFrontGateOpenChange()  {
  // Add your code here to act upon FrontGateOpen change
}

/*
  Since FrontGatePersonalOpen is READ_WRITE variable, onFrontGatePersonalOpenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFrontGatePersonalOpenChange()  {
  // Add your code here to act upon FrontGatePersonalOpen change
}
