// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "814828a1-2b92-4f13-b093-8a74253090fa";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "w#hwlZtloU2MYJMV!9fuitN6E";    // Secret device password

void onFrontGateCloseChange();
void onFrontGateOpenChange();
void onFrontGatePersonalOpenChange();

String gate_Status;
CloudContactSensor gate_Close;
CloudContactSensor gate_Open;
CloudSwitch front_Gate_Close;
CloudSwitch front_Gate_Open;
CloudSwitch front_Gate_Personal_Open;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gate_Status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gate_Close, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gate_Open, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(front_Gate_Close, READWRITE, ON_CHANGE, onFrontGateCloseChange);
  ArduinoCloud.addProperty(front_Gate_Open, READWRITE, ON_CHANGE, onFrontGateOpenChange);
  ArduinoCloud.addProperty(front_Gate_Personal_Open, READWRITE, ON_CHANGE, onFrontGatePersonalOpenChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
