# Installer files for new starts.

import time
from subprocess import call
time.sleep(2)
call("sudo apt-get update && sudo apt-get upgrade -y", shell=True)
time.sleep(2)
call("sudo apt install -y build-essential -y", shell=True)
time.sleep(2)
call("sudo apt install python3 -y", shell=True)
time.sleep(2)
call("sudo apt-get install python3-full -y, shell=True)
time.sleep(2)
call("sudo apt install python3 pip -y", shell=True)
time.sleep(2)
call("sudo apt install remoteit -y", shell=True)
time.sleep(2)
call("sudo apt install connectd -y", shell=True)
time.sleep(2)
call("sudo pip3 install pyserial -y --break-system-packages", shell=True)
time.sleep(2)
call("sudo pip3 Adafruit_DHT -y --break-system-packages", shell=True)
time.sleep(2)
call("sudo apt install python3 GPIO -y", shell=True)
time.sleep(2)
call("pip3 install piicodev --break-system-packages", shell=True)
time.sleep(2)
call("sudo apt install git -y", shell=True)
time.sleep(2)
call("pip3 install piicodev -y --break-system-packages", shell=True)
time.sleep(2)
call("pip3 install --upgrade setuptools --break-system-packages", shell=True)
time.sleep(2)
call("pip3 install --upgrade gcloud --break-system-packages", shell=True)
time.sleep(2)
call("pip3 install pycryptodome==3.4.3 --break-system-packages", shell=True)

call("pip3 install pyrebase --break-system-packages", shell=True)
